services:
  qdrant:
    image: qdrant/qdrant:v1.11.3
    container_name: qdrant-container
    restart: unless-stopped
    environment:
      QDRANT__SERVICE__GRPC_PORT: 6334
      QDRANT__SERVICE__HTTP_PORT: 6333
      QDRANT__SERVICE__API_KEY: ${QDRANT_API_KEY}
    ports:
      - "6333:6333" # REST API
      - "6334:6334" # gRPC API
    volumes:
      - qdrant-data:/qdrant/storage
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:6333/health",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  qdrant-data:
    driver: local
